# Generated by Django 5.1.3 on 2025-01-02 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nails', '0003_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product_name',
        ),
    ]
