# Generated by Django 5.1.3 on 2025-01-08 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nails', '0006_alter_carouselimage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
