# Generated by Django 5.1.3 on 2025-01-08 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nails', '0007_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='measurements',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='measurements',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
