# Generated by Django 5.1.3 on 2025-01-14 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nails', '0008_remove_order_measurements_orderitem_measurements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='measurements',
        ),
        migrations.AddField(
            model_name='order',
            name='measurements',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
