# Generated by Django 5.1.3 on 2025-02-21 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nails', '0009_remove_orderitem_measurements_order_measurements'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='requires_measurements',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(upload_to='products/'),
        ),
    ]
