# Generated by Django 5.1.3 on 2025-02-21 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nails', '0010_product_requires_measurements_alter_product_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='measurements',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
