# Generated by Django 5.1.3 on 2025-02-21 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nails', '0011_orderitem_measurements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='measurements',
        ),
    ]
