# Generated by Django 5.1.3 on 2025-02-22 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nails', '0012_remove_order_measurements'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='pending', max_length=20),
        ),
    ]
